### ISSUE TITLE
Identity-lab: No matches for kind "VaultConnection" & "VaultAuth"

### ISSUE THREAD

**Issue by KyleZevenbergen** [nicolaka/hashicorp#2]
I got to step 5 in the identity lab (plan and apply) and two errors popped up.

Error: Failed to determine GroupVersionResource for manifest

with kubernetes_manifest.blue-vault-connection-default,
on deployment.tf line 141, in resource "kubernetes_manifest" "blue-vault-connection-default":
141: resource "kubernetes_manifest" "blue-vault-connection-default" {

no matches for kind "VaultConnection" in group "secrets.hashicorp.com"

-----

Error: Failed to determine GroupVersionResource for manifest
with kubernetes_manifest.blue-vault-auth-default,
on deployment.tf line 160, in resource "kubernetes_manifest" "blue-vault-auth-default":
160: resource "kubernetes_manifest" "blue-vault-auth-default" {

no matches for kind "VaultAuth" in group "secrets.hashicorp.com"

**Comment by nicolaka** [comment]
@KyleZevenbergen good catch. The VSO helm chart will deploy VSO and create the required CRDs (e.g VaultConnection) so try adding `depends_on = [ helm_release.vso]` under both blue-vault-connection-default and blue-vault-auth-default in deployment.tf and let me know if that resolves it ?

**Comment by KyleZevenbergen** [comment]
Seems like it didn't resolve it.

<img width="1046" alt="Screenshot 2024-02-12 at 8 49 17 AM" src="https://github.com/nicolaka/hashicorp/assets/15393043/b9262627-4d39-4ded-a031-cd6e18bfb4b6">

**Comment by nicolaka** [comment]
fixed in latest commit
